### PR TITLE
Add support for a -config flag/file

### PR DESCRIPTION
**Pull request by bcspragu**
This PR adds support for a `-config` flag, as described in the docs for
the `github.com/peterbourgon/ff/v3` package.

The motivation for this is to support deployments where the config
will be stored in some secret management system and loaded wholesale.

### CODE REVIEW

**Comment by cshum** [comment]
Is there any benefit using "-config" style config file? Seems it is neither a standard format nor used mainstream.

What about extending the current `.env` to accept a custom file path?
https://github.com/cshum/imagor/blob/master/cmd/imagor/main.go#L37

**Comment by bcspragu** [comment]
Great idea, I'll do that. I'm used to using the [namsral/flag](https://pkg.go.dev/github.com/namsral/flag) package, which does command line args, env variables, and `.env` style files, so I totally missed that a library like `godotenv` was being used. I'll do that.

**Comment by bcspragu** [comment]
Actually, looking at this more, it's kind of a chicken and egg problem. We want to optionally load ENV vars from a flag, but the env vars are used in flag parsing. There's ~two ways we could do this:

1. Split flag parsing into two steps, one for just the `-config` flag, and one for everything else, or
2. Replace both `github.com/peterbourgon/ff/v3` and `github.com/joho/godotenv` with something like [`github.com/namsral/flag`](https://pkg.go.dev/github.com/namsral/flag), which will handle env files via `-config` transparently.

**Comment by cshum** [comment]
I took a quick glance at https://github.com/namsral/flag. Its latest commit was in 2017 and forks have been made https://github.com/namsral/flag/issues/36. Their `BSD-3` licensing is more permissive. Their example code does not look like a feature parity either. 

`ff` seems to be a more well thought out and maintained package imo. What about trying out their `v3.2.0-rc.1`? 
https://github.com/peterbourgon/ff/commit/72c982b14dc7ec91eea69392b80dc9934cd00c33
Seems replacing `ff.PlainParser ` with `ff.EnvParser` would do the job. This will allow trimming off `godotenv` also

**Comment by bcspragu** [comment]
Ah nice, didn't realize `ff` had an env parser. I've updated the version, removed `godotenv`, switched to `ff.EnvParser`, and updated the example in the README. I also tested it out and it works great.

**Pull request merged**
