### PR TITLE
add -server-debug-listen flag to enable pprof

### PR DESCRIPTION
**Pull request by thomasf**

### CODE REVIEW

**Comment by cshum** [comment]
It seems to add a bit of confusion with the existing `-debug` flag. What about either of them:

1. simply enable pprof is `-debug` flag is set
2. name it`-server-pprof-listen`

I tend to prefer 1. because it seems to achieve the goal without any additional config? 

These are just my quick thoughts. Do let me know if I am missing any details.

**Comment by thomasf** [comment]
You are right, I was not sure  which way to go. 

I am thinking that the if possibly future HTTP enabled debug tools could be enabled using the same `-server-debug-listen`. It would already be very bad to enable this towards the public internet so adding more powerful (dangerous) debug tools to it isn't a big issue.

`-debug` does to be targeted at local development because it changes things like log formatting while pprof is valuable on its own in production/staging to measure how imagor behaves under production load.

**Comment by thomasf** [comment]
Maybe debug isn't a good name for it at all. I would personally prefer to put stuff like metrics exporters on that HTTP listener rather than the default one.

**Comment by thomasf** [comment]
I'm closing this for now. Not sure how the most commonly useful way to go about it would be.  It is probably useful for some people to have this built in but I have done my initial profiling already with a patched version of imagor and don't expect to need it again soon.

**Pull request closed without merging**
